In [1]:
!pip install emoji

     |████████████████████████████████| 170 kB 13.7 MB/s 
  Created wheel for emoji: filename=emoji-1.6.1-py3-none-any.whl size=169314 sha256=d6253fa8ed07d36d7ddd1dc230d283c0ecacbb00e0fd79ddf65f1e7272d2c67f
  Stored in directory: /root/.cache/pip/wheels/ea/5f/d3/03d313ddb3c2a1a427bb4690f1621eea60fe6f2a30cc95940f
Successfully built emoji


In [2]:
import emoji

In [3]:
len(emoji.EMOJI_UNICODE['en'])

3633

In [4]:
emoji.EMOJI_UNICODE['en']

{':1st_place_medal:': '🥇',
 ':2nd_place_medal:': '🥈',
 ':3rd_place_medal:': '🥉',
 ':AB_button_(blood_type):': '🆎',
 ':ATM_sign:': '🏧',
 ':A_button_(blood_type):': '🅰️',
 ':Afghanistan:': '🇦🇫',
 ':Albania:': '🇦🇱',
 ':Algeria:': '🇩🇿',
 ':American_Samoa:': '🇦🇸',
 ':Andorra:': '🇦🇩',
 ':Angola:': '🇦🇴',
 ':Anguilla:': '🇦🇮',
 ':Antarctica:': '🇦🇶',
 ':Antigua_&_Barbuda:': '🇦🇬',
 ':Aquarius:': '♒',
 ':Argentina:': '🇦🇷',
 ':Aries:': '♈',
 ':Armenia:': '🇦🇲',
 ':Aruba:': '🇦🇼',
 ':Ascension_Island:': '🇦🇨',
 ':Australia:': '🇦🇺',
 ':Austria:': '🇦🇹',
 ':Azerbaijan:': '🇦🇿',
 ':BACK_arrow:': '🔙',
 ':B_button_(blood_type):': '🅱️',
 ':Bahamas:': '🇧🇸',
 ':Bahrain:': '🇧🇭',
 ':Bangladesh:': '🇧🇩',
 ':Barbados:': '🇧🇧',
 ':Belarus:': '🇧🇾',
 ':Belgium:': '🇧🇪',
 ':Belize:': '🇧🇿',
 ':Benin:': '🇧🇯',
 ':Bermuda:': '🇧🇲',
 ':Bhutan:': '🇧🇹',
 ':Bolivia:': '🇧🇴',
 ':Bosnia_&_Herzegovina:': '🇧🇦',
 ':Botswana:': '🇧🇼',
 ':Bouvet_Island:': '🇧🇻',
 ':Brazil:': '🇧🇷',
 ':British_Indian_Ocean_Territory:': '🇮🇴',
 ':British_Virgin_

In [5]:
emoji.emojize(':baseball:')

'⚾'

In [8]:
emoji_dict = {      "0": "\u2764\uFE0F",    
                    "1": ":basketball:",
                    "2": ":beaming_face_with_smiling_eyes:",
                    "3": ":downcast_face_with_sweat:",
                    "4": ":fork_and_knife:",
             }

In [9]:
for e in emoji_dict.values():
    print(emoji.emojize(e))

❤️
🏀
😁
😓
🍴


#Read Data

In [10]:
import pandas as pd

In [12]:
train  = pd.read_csv("/content/train_emoji.csv", header = None)
test = pd.read_csv("/content/test_emoji.csv", header=None)

In [13]:
train.drop(columns=[2,3], inplace=True)

In [14]:
train.columns = ['Text', 'Label']
test.columns = ['Text', 'Label']

In [15]:
train.head()

Text  Label
0           never talk to me again      3
1  I am proud of your achievements      2
2   It is the worst day in my life      3
3                 Miss you so much      0
4                     food is life      4

In [16]:
test['Text']  = test['Text'].apply(lambda x : x[:-1])

In [17]:
test.head()

Text  Label
0             I want to eat      4
1         he did not answer      3
2            he got a raise      2
3      she got me a present      0
4  ha ha ha it was so funny      2

In [18]:
X_train = train['Text'].values
y_train = train['Label'].values

X_test = test['Text'].values
y_test = test['Label'].values

In [19]:
X_train[:5]

array(['never talk to me again', 'I am proud of your achievements',
       'It is the worst day in my life', 'Miss you so much',
       'food is life'], dtype=object)

In [20]:
y_train

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1, 3, 3, 1, 3, 2, 3, 2, 3, 1, 2, 3, 0,
       2, 2, 2, 1, 4, 2, 2, 4, 0, 3, 4, 2, 0, 3, 2, 2, 3, 4, 2, 2, 0, 2,
       3, 0, 3, 2, 4, 3, 0, 3, 3, 3, 4, 2, 1, 1, 1, 2, 3, 1, 0, 0, 0, 3,
       4, 4, 2, 2, 1, 2, 0, 3, 2, 2, 0, 0, 3, 1, 2, 1, 2, 2, 4, 3, 3, 2,
       4, 0, 0, 0, 3, 3, 3, 2, 0, 1, 2, 3, 0, 2, 2, 2, 3, 2, 2, 2, 4, 1,
       1, 3, 3, 4, 1, 2, 1, 1, 3, 1, 0, 4, 0, 3, 3, 4, 4, 1, 4, 3, 0, 2])

In [21]:
X_train.shape, y_train.shape

((132,), (132,))

In [22]:
X_test.shape, y_test.shape

((56,), (56,))

In [23]:
for i in range(15, 23):
    print(X_train[i], emoji.emojize( emoji_dict[str(y_train[i])]) )

Stop shouting at me 😓
Sounds like a fun plan ha ha 😁
no one likes him 😓
the game just finished 🏀
I will celebrate soon 😁
So sad you are not coming 😓
She is my dearest love ❤️
Good job 😁


#Get Embedding 

In [24]:
import numpy as np

In [26]:
!wget http://nlp.stanford.edu/data/glove.6B.zip

--2022-01-02 08:40:03--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2022-01-02 08:40:04--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2022-01-02 08:40:04--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip’

glove.6

In [27]:
!unzip glove*.zip

Archive:  glove.6B.zip
  inflating: glove.6B.50d.txt        
  inflating: glove.6B.100d.txt       
  inflating: glove.6B.200d.txt       
  inflating: glove.6B.300d.txt       


In [28]:
f = open("glove.6B.50d.txt", encoding='utf8')

In [29]:
embedding_matrix = {}

In [30]:
for line in f:
    
    values = line.split()
    word = values[0]
    emb = np.array(values[1:], dtype='float')
    
    embedding_matrix[word] = emb

In [32]:
embedding_matrix['the'].shape

(50,)

In [33]:
def get_embedding_matrix_for_data(data):
    maxLen = 10
    embedding_data = np.zeros( (len(data), maxLen, 50) )
    
    for ix in range(data.shape[0]):
        words_in_sen = data[ix].split()
        
        for ij in range(len(words_in_sen)):
            if embedding_matrix.get(words_in_sen[ij].lower()) is not None:
                embedding_data[ix][ij] =  embedding_matrix[words_in_sen[ij].lower()]
        
    return embedding_data

In [34]:
X_train = get_embedding_matrix_for_data(X_train)

In [35]:
X_test = get_embedding_matrix_for_data(X_test)

In [36]:
X_train.shape

(132, 10, 50)

In [37]:
X_test.shape

(56, 10, 50)

In [38]:
from tensorflow.keras.utils import to_categorical

In [39]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [40]:
y_train.shape

(132, 5)

In [41]:
y_test.shape

(56, 5)

#RNN/LSTM Model

In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, SimpleRNN, Dense, Dropout

In [43]:
model = Sequential()
model.add( LSTM(units=64, input_shape=(10,50), return_sequences = True ) )
model.add( Dropout(0.3) )
model.add( LSTM(units=32) )
model.add(Dropout(0.2))
model.add(Dense(units=10, activation = 'relu'))
model.add(Dense(units=5, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 10, 64)            29440     
                                                                 
 dropout (Dropout)           (None, 10, 64)            0         
                                                                 
 lstm_1 (LSTM)               (None, 32)                12416     
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                                 
 dense (Dense)               (None, 10)                330       
                                                                 
 dense_1 (Dense)             (None, 5)                 55        
                                                                 
Total params: 42,241
Trainable params: 42,241
Non-traina

In [44]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics= ['accuracy'])

In [45]:
his = model.fit(X_train, y_train, validation_split=0.1, batch_size=32, epochs= 50 )

Epoch 1/50
4/4 [==============================] - 9s 528ms/step - loss: 1.6041 - accuracy: 0.2288 - val_loss: 1.6158 - val_accuracy: 0.2857
Epoch 2/50
4/4 [==============================] - 0s 25ms/step - loss: 1.5670 - accuracy: 0.3390 - val_loss: 1.6200 - val_accuracy: 0.1429
Epoch 3/50
4/4 [==============================] - 0s 19ms/step - loss: 1.5333 - accuracy: 0.3814 - val_loss: 1.6165 - val_accuracy: 0.3571
Epoch 4/50
4/4 [==============================] - 0s 21ms/step - loss: 1.5133 - accuracy: 0.3898 - val_loss: 1.6036 - val_accuracy: 0.3571
Epoch 5/50
4/4 [==============================] - 0s 19ms/step - loss: 1.4732 - accuracy: 0.4237 - val_loss: 1.6349 - val_accuracy: 0.3571
Epoch 6/50
4/4 [==============================] - 0s 19ms/step - loss: 1.4507 - accuracy: 0.4576 - val_loss: 1.6613 - val_accuracy: 0.1429
Epoch 7/50
4/4 [==============================] - 0s 22ms/step - loss: 1.4144 - accuracy: 0.4492 - val_loss: 1.6074 - val_accuracy: 0.3571
Epoch 8/50
4/4 [==========

In [46]:
model.evaluate(X_train, y_train)

5/5 [==============================] - 0s 6ms/step - loss: 0.1275 - accuracy: 0.9773


[0.127458855509758, 0.9772727489471436]

In [47]:
model.evaluate(X_test , y_test)

2/2 [==============================] - 0s 16ms/step - loss: 1.6455 - accuracy: 0.5893


[1.645520806312561, 0.5892857313156128]

#Predictions

In [51]:
y_pred = np.argmax(model.predict(X_test), axis=-1)

In [52]:
y_pred

array([4, 3, 3, 0, 2, 2, 3, 2, 4, 2, 1, 2, 0, 3, 1, 3, 3, 2, 3, 2, 0, 0,
       4, 0, 3, 3, 2, 0, 1, 2, 0, 1, 3, 2, 0, 1, 2, 0, 1, 2, 1, 0, 0, 1,
       2, 2, 3, 2, 3, 3, 3, 3, 3, 2, 3, 0])

In [53]:
np.argmax(y_test, axis=1)

array([4, 3, 2, 0, 2, 0, 0, 0, 4, 2, 1, 3, 3, 2, 1, 3, 3, 2, 3, 4, 0, 2,
       4, 3, 3, 3, 3, 0, 2, 0, 0, 1, 3, 2, 0, 1, 2, 4, 4, 2, 2, 2, 0, 1,
       2, 0, 2, 2, 2, 3, 3, 0, 3, 2, 2, 3])

In [54]:
for t in range(len(test)):
    print(test['Text'].iloc[t])
    print("Prediction : ",  emoji.emojize(emoji_dict[str(y_pred[t])]) )
    print("Actual : ", emoji.emojize(emoji_dict[str( test['Label'].iloc[t] )]) )
    print()

I want to eat
Prediction :  🍴
Actual :  🍴

he did not answer
Prediction :  😓
Actual :  😓

he got a raise
Prediction :  😓
Actual :  😁

she got me a present
Prediction :  ❤️
Actual :  ❤️

ha ha ha it was so funny
Prediction :  😁
Actual :  😁

he is a good friend
Prediction :  😁
Actual :  ❤️

I am upset
Prediction :  😓
Actual :  ❤️

We had such a lovely dinner tonight
Prediction :  😁
Actual :  ❤️

where is the food
Prediction :  🍴
Actual :  🍴

Stop making this joke ha ha ha
Prediction :  😁
Actual :  😁

where is the ball
Prediction :  🏀
Actual :  🏀

work is hard
Prediction :  😁
Actual :  😓

This girl is messing with me
Prediction :  ❤️
Actual :  😓

are you serious ha ha
Prediction :  😓
Actual :  😁

Let us go play baseball
Prediction :  🏀
Actual :  🏀

This stupid grader is not working 
Prediction :  😓
Actual :  😓

work is horrible
Prediction :  😓
Actual :  😓

Congratulation for having a baby
Prediction :  😁
Actual :  😁

stop messing around
Prediction :  😓
Actual :  😓

any suggestions for din

#Prediction For Custom Text

In [55]:
inp  = "where is the ball"

In [56]:
inp

'where is the ball'

In [57]:
embedding_x_query = []

In [58]:
for w in inp.lower().split():
    print(w)
    e = embedding_matrix[w]
    embedding_x_query.append(e)

where
is
the
ball


In [59]:
embedding_x_query = np.array(embedding_x_query)

In [60]:
embedding_x_query.shape

(4, 50)

In [61]:
if embedding_x_query.shape[0] < 10:
    embedding_x_query = np.vstack( (embedding_x_query, np.zeros((10 - len(embedding_x_query) , 50))  ) )

In [62]:
embedding_x_query.shape

(10, 50)

In [63]:
embedding_x_query = embedding_x_query.reshape(1, 10, 50)

In [64]:
embedding_x_query.shape

(1, 10, 50)

In [66]:
pred = np.argmax(model.predict(embedding_x_query), axis=-1)

In [67]:
emoji.emojize( emoji_dict[ str(pred[0])] )

'🏀'